
image: docker:latest

services:
  - docker:dind
before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:          # List of stages for jobs, and their order of execution
  - fetch
  - build
  - test

fetching-github-changes   # This job runs in the fetch stage. it indicates that changes from remote repository were detected
  stage: fetch
  script:    
    - echo "Github changes fecthing"
    - echo "Changes saved"

build-job:       # This job runs in the docker build stage and pushing image to dockerhub.
  stage: build
  script:
    - echo "Building docker image the code..."
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - echo "Build complete."
    - echo "Pushing image to dockerhub repository..."
    - docker image push "$CI_REGISTRY_IMAGE"
    - echo "Image  successfully pushed ."     
  only:
    - main


deploy-job:      # This job runs in the test stage.
  stage: test  # It indicates tests and results after the build .
  script:
    - echo "finished"
    
